```python

from pychrono import *

from pychrono.Irrlicht import *


def create_epicyclic_gears_simulation():

    

    sim = ChSystemNSC()


    

    truss = ChBody()

    truss.SetBodyFixed(True)

    truss.SetMass(1000.0)


    

    bar = ChBody()

    bar.SetBodyFixed(False)

    bar.SetMass(50.0)

    bar.SetPosition(ChVectorD(0, 0, 0))


    

    gear1 = ChLink6D()

    gear1.SetName("Gear1")

    gear1.Init(bar, gear1, 0, 0, 0, 0, 0, 0)

    gear1.SetMotor(True)

    gear1 = ChBody()

    truss = ChBody()

    truss.SetName("Fixed Truss")

    truss.SetMass(1000.0)

    truss.SetPosition(ChVector3(0, 0, 0)

    truss.SetVisualMaterial("Fixed Truss")


    

    bar = ChBody()

    bar.SetName("Rotating Bar")

    bar.SetMass(50.0)

    bar.SetPosition(ChVector3(0, 0, 0)

    bar.SetVisualMaterial("Rotating Bar")


    

    gear1 = ChLink6D(truss)

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()

    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.Init()

    gear1.Init()
    gear1.`


    

    sim.AddBody(truss)

    sim.AddBody(bar)

    sim.AddLink(gear1)


    

    gearMotor = ChPulley(gear1, ChVector3(0, 0, 0), 1.0)

    gearMotor.Init()

    gearMotor.Init()

    gearMotor.Init()

    gearMotor.Init()

    gearMotor.Init()

    gearMotor.Init()

    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gearMotor.Init()
    gear