import pychrono.core as chrono
import pychrono.sensor as sens

import numpy as np
import time
import math

def main():
    
    
    
    
    os = chrono.ChSystemNSC()

    
    math = chrono.ChMath()

    
    np = chrono.ChNumPy()

    
    chrono = chrono.ChSystem()

    
    robot = chrono.ChRobot()

    
    irrlicht = chrono.ChIrrlicht()

    
    vehicle = chrono.ChVehicle()

    
    
    
    
    
    mphysicalSystem = chrono.ChSystemNSC()

    
    
    
    material_nsc = chrono.ChContactMaterialNSC()

    
    material_smc = chrono.ChContactMaterialSMC()

    
    material_nsc = chrono.ChContactMaterialNSC()

    
    material_smc = chrono.ChContactMaterialSMC()

    
    
    
    
    
    chrono.ChCollisionModel.SetDefaultSuggestedEnvelope(0.01)

    
    
    chrono.ChCollisionModel.SetDefaultSuggestedMargin(0.005)

    
    
    
    
    body = chrono.ChBody()

    
    sphere = chrono.ChVisualShapeSphere(1.0, 1.0, 1.0)
    sphere.SetPos(chrono.ChVector3d(0, 0, 0))
    sphere.SetFixed(True)

    
    box = chrono.ChBodyEasyBox(1.0, 1.0, 1.0, 1000)
    box.SetPos(chrono.ChVector3d(0, 0, 0))
    box.SetFixed(True)

    
    camera = chrono.ChCamera()
    camera.SetPosition(chrono.ChVector3d(0, 0, 0))
    camera.SetRotation(chrono.ChVector3d(0, 0, 0))

    
    
    
    
    
    rev_joint = chrono.ChLinkLockRevolute()
    rev_joint.Initialize(body, box, chrono.ChCoordsysD(chrono.ChVector3d(0, 0, 0)))

    
    
    pris_joint = chrono.ChLinkLockPrismatic()
    pris_joint.Initialize(body, box, chrono.ChCoordsysD(chrono.ChVector3d(0, 0, 0)))

    
    
    spherical_joint = chrono.ChLinkLockSpherical()
    spherical_joint.Initialize(body, box, chrono.ChCoordsysD(chrono.ChVector3d(0, 0, 0)))

    
    
    
    
    
    
    if vis:
        
        vis.AttachSystem(body)
        vis.SetWindowSize(1024, 768)
        vis.SetWindowTitle('Simulation Window')
        vis.AddLogo(chrono.GetChronoDataFile('logo_pychrono_alpha.png'))
        vis.AddTypicalLights()
        vis.SetColor(chrono.ChColor(1, 0, 0))
        vis.SetColor(chrono.ChColor(0, 1, 0))
        vis.SetColor(chrono.ChColor(0, 0, 1))
        vis.SetColor(chrono.ChColor(1, 0, 0))
        vis.SetColor(chrono.ChColor(0, 1, 0))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor(1, 0, 1))
        vis.SetColor(chrono.ChColor(0, 1, 1))
        vis.SetColor(chrono.ChColor
print("error happened with only start ```python")