import pychrono as chrono
import pyirrlicht as
import pyvehicle as veh
math


chrono.SetChronoPath(GetDataPath())
veh.SetPath(GetChronoData() + vehicle)


Loc chronoVector3d(0,0,0.0)
init = chrono.Qunit

vis = veh.Mesh

assis_type = NONE

terrain = veh.BOX
Height = 0      
terrain =100.0 
terrain =100.0 


track = chronoVectord(0.0,0.0.0)

 = SMC

step =5e
tire_size = step

render = 1.0 /50


vehicle = veh113()
vehicle.SetContact( S)
vehicle.SetTrackoeve(Trackoe)
vehicle.Setline(veType)
vehicle.Setineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineineine
print("error happened with only start ```python")