```python

import pychrono as chrono
import pychrono.irrlicht as chronoirr
import pychrono.postprocess as postprocess


chrono.Ch纪元().Initialize()


man_10t = chrono.ChVehicle()
man_10t.SetName("MAN_10t")
man_10t.Initialize()


man_10t.SetMass(10000.0)
man_10t.SetInertia(chrono.ChVectorD(1000.0, 1000.0, 1000.0))


tire_model = chrono.ChTMEASY()
tire_model.Initialize(man_10t)


tire_model.SetPressure(2.0)
tire_model.SetTireRadius(0.3)


steering_control = chrono.ChSteeringControl()
steering_control.SetMaxSteeringAngle(chrono.CH_C_PI_2)

throttle_control = chrono.ChThrottleControl()
throttle_control.SetMaxThrottle(1.0)

brake_control = chrono.ChBrakeControl()
brake_control.SetMaxBrakeTorque(10000.0)


vis_sys = chronoirr.ChVisualSystemIrrlicht()
vis_sys.AttachSystem(man_10t.GetSystem())
vis_sys.SetWindowSize(800, 600)
vis_sys.SetWindowTitle("MAN 10t Truck Simulation")


vis_sys.AddLogo(chrono.GetChronoDataFile("logo_pychrono_alpha.png"))
vis_sys.AddSkyBox()
vis_sys.AddDirectionalLight(chrono.ChVectorD(1, 1, 1))
vis_sys.AddAmbientLight(chrono.ChVectorD(0.5, 0.5, 0.5))


terrain_texture = chrono.ChTexture()
terrain_texture.SetFilename(chrono.GetChronoDataFile("terrain/grass.jpg"))
terrain_texture.SetUVRepeat(chrono.ChUVRepeat(10, 10))
terrain_texture.SetUVOffset(chrono.ChUVOffset(0.5, 0.5))
terrain_texture.SetUVScale(chrono.ChUVScale(1000.0, 1000.0))
terrain_texture.SetUVTranslation(chrono.ChUVTranslation(0.0, 0.0))
terrain_texture.SetUVRotation(chrono.ChUVRotation(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotationTexture(0.0, 0.0, 0.0))
terrain_texture.SetUVScaleTexture(chrono.ChUVScaleTexture(1.0, 1.0))
terrain_texture.SetUVTranslationTexture(chrono.ChUVTranslationTexture(0.0, 0.0))
terrain_texture.SetUVRotationTexture(chrono.ChUVRotation