Here is the corrected and modified script based on the given instructions:

```python
import pychrono as ch
import pychrono.vehicle as veh
import pychrono.ros as chros
from pychrono import irrlicht as chronoirr
import math
import pychrono.sensor as sens

def main():
    veh.SetDataPath(ch.GetChronoDataPath() + 'vehicle/')
    
    hmmwv = veh.HMMWV_Full()
    hmmwv.SetContactMethod(ch.ChContactMethod_NSC)  
    hmmwv.SetChassisCollisionType(veh.CollisionType_NONE)  
    hmmwv.SetChassisFixed(False)  
    hmmwv.SetInitPosition(ch.ChCoordsysd(ch.ChVector3d(0, 0, 1.6), ch.ChQuaterniond(1, 0, 0, 0)))  
    hmmwv.SetEngineType(veh.EngineModelType_SHAFTS)  
    hmmwv.SetTransmissionType(veh.TransmissionModelType_AUTOMATIC_SHAFTS)  
    hmmwv.SetDriveType(veh.DrivelineTypeWV_AWD)  
    hmmwv.SetSteeringType(veh.SteeringTypeWV_PITMAN_ARM)  
    hmmwv.SetTireType(veh.TireModelType_TMEASY)  
    hmmwv.SetTireStepSize(1e-3)  
    hmmwv.Initialize()  
    hmmwv.SetChassisVisualizationType(veh.VisualizationType_MESH)
    hmmwv.SetSuspensionVisualizationType(veh.VisualizationType_MESH)
    hmmwv.SetSteeringVisualizationType(veh.VisualizationType_MESH)
    hmmwv.SetWheelVisualizationType(veh.VisualizationType_MESH)
    hmmwv.SetTireVisualizationType(veh.VisualizationType_MESH)
    
    terrain = veh.RigidTerrain(hmmwv.GetSystem())
    patch_mat = ch.ChContactMaterialNSC()  
    patch_mat.SetFriction(0.9)  
    patch_mat.SetRestitution(0.01)  
    patch = terrain.AddPatch(patch_mat, ch.CSYSNORM, 100.0, 100.0)  
    patch.SetTexture(veh.GetDataFile("terrain/textures/tile4.jpg"), 100, 100)
    terrain.Initialize()  
    
    vis = chronoirr.ChVisualSystemIrrlicht()
    vis.AttachSystem(hmmwv.GetSystem())
    vis.SetCameraVertical(ch.CameraVerticalDir_Z)
    vis.SetWindowSize(1280, 720)
    vis.SetWindowTitle('Viper rover - Rigid terrain')
    vis.Initialize()
    vis.AddLogo(ch.GetChronoDataFile('logo_pychrono_alpha.png'))
    vis.AddSkyBox()
    vis.AddCamera(ch.ChVector3d(-5, 2.5, 1.5), ch.ChVector3d(0, 0, 1))
    vis.AddTypicalLights()
    vis.AddLightWithShadow(ch.ChVector3d(1.5, -2.5, 5.5), ch.ChVector3d(0, 0, 0.5), 3, 4, 10, 40, 512)

    
    driver = veh.ChDriver(hmmwv.GetVehicle())
    driver.Initialize()  

    
    ros_manager = chros.ChROSPythonManager()
    ros_manager.RegisterHandler(chros.ChROSClockHandler())  
    
    ros_manager.RegisterHandler(chros.ChROSDriverInputsHandler(25, driver, "~/input/driver_inputs"))
    
    ros_manager.RegisterHandler(chros.ChROSBodyHandler(25, hmmwv.GetChassisBody(), "~/output/hmmwv/state"))
    ros_manager.Initialize()  

    
    sens_manager = sens.ChSensorManager(hmmwv.GetSystem())

    
    lidar = sens.ChLidarSensor(hmmwv.GetChassisBody(), sens.ChVector<>(0, 0, 0.5))
    lidar.SetName("lidar")
    lidar.SetFrequency(20)
    lidar.SetNumRays(100)
    lidar.SetRange(10)
    lidar.SetVerticalAngle(-20, 20)
    lidar.SetFilter(sens.ChFilterAccess::F_RAY, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_POINTCLOUD, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_INTENSITY, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_DISTANCE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_OUTLIERS, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_CLUSTERING, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_SEGMENTATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_TRACKING, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_OBJECT_RECOGNITION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DUPLICATES, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_PLANE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GROUND, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_VEHICLE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_PEDESTRIAN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_CYCLIST, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_ANIMAL, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_OTHER, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFRACTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_LOOP_CLOSURE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_GLOBAL_LOCALIZATION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_KINEMATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_DYNAMIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_STATIC, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_UNKNOWN, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_NOISE, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_SHADOW, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REFLECTION, sens.ChFilterAccess::FILTER_NONE)
    lidar.SetFilter(sens.ChFilterAccess::F_REMOVE_REF