chrono.SetChrono().Initialize();
    chrono.SetChrono().SetDataPath(chrono.GetDataFile("chronodata/"));
    chrono.SetChron().SetChronoDataPath(chrono.GetDataFile("chrono/data"));
    sys = chrono.ChSystem();
 sys.Add(sys, chrono.ChBody);
 sys.Add, driver;
 sys.Add, vipersensor;
 sys.Add vipers;
 sys.Add chassi;
 sys.Add ch;
sys.Add v;
sys.Add chassi;
sys.Add ch;
sys.Add v;
sys.Add chassi;
sys ch;
sys.Add ch;
sys.Add chassi;
sys chassi;
sys.Add chsys;
sys chsys chassi;
sys chassi
    sys.Add vipers;
sys.Add chassi;
sys chassi chassi sysassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassiassi
print("error happened with only start ```python")