```python
import pychrono as ch
import pychrono.vehicle as veh
import pychrono.ros as chros
from pychrono import irrlicht as chronoirr  

def main():
    
    hmmwv = veh.HMMWV_Full()
    hmmwv.SetContactMethod(ch.ChContactMethod_NSC)  
    hmmwv.SetChassisCollisionType(veh.CollisionType_NONE)  
    hmmwv.SetChassisFixed(False)  
    hmmwv.SetInitPosition(ch.ChCoordsysd(ch.ChVector3d(0, 0, 1.6), ch.ChQuaterniond(1, 0, 0, 0)))  
    hmmwv.SetEngineType(veh.EngineModelType_SHAFTS)  
    hmmwv.SetTransmissionType(veh.TransmissionModelType_AUTOMATIC_SHAFTS)  
    hmmwv.SetDriveType(veh.DrivelineTypeWV_AWD)  
    hmmwv.SetSteeringType(veh.SteeringTypeWV_PITMAN_ARM)  
    hmmwv.SetTireType(veh.TireModelType_TMEASY)  
    hmmwv.SetTireStepSize(1e-3)  
    hmmwv.Initialize()  

    
    hmmwv.SetChassisVisualizationType(veh.ChVisualizationType_MESH)
    hmmwv.SetSuspensionVisualizationType(veh.ChVisualizationType_MESH)
    hmmwv.SetSteeringVisualizationType(veh.ChVisualizationType_MESH)
    hmmwv.SetWheelVisualizationType(veh.ChVisualizationType_MESH)
    hmmwv.SetTireVisualizationType(veh.ChVisualizationType_MESH)

    
    terrain = veh.RigidTerrain(hmmwv.GetSystem())
    patch_mat = ch.ChContactMaterialNSC()  
    patch_mat.SetFriction(0.9)  
    patch_mat.SetRestitution(0.01)  
    patch = terrain.AddPatch(patch_mat, ch.CSYSNORM, 100.0, 100.0)  
    patch.SetTexture(veh.GetDataFile("terrain/textures/tile4.jpg"), 100, 100)  
    terrain.Initialize()  

    
    driver = veh.ChDriver(hmmwv.GetVehicle())
    driver.Initialize()  

    
    ros_manager = chros.ChROSPythonManager()
    ros_manager.RegisterHandler(chros.ChROSClockHandler())  
    ros_manager.RegisterHandler(chros.ChROSDriverInputsHandler(25, driver, "~/input/driver_inputs"))
    ros_manager.RegisterHandler(chros.ChROSBodyHandler(25, hmmwv.GetChassisBody(), "~/output/hmmwv/state"))
    ros_manager.Initialize()  

    
    veh.SetDataPath(ch.GetChronoDataPath() + 'vehicle/')

    
    vis = chronoirr.ChVisualSystemIrrlicht()

    
    vis.SetWindowName("HMMWV Simulation")
    vis.SetVisible(True)
    vis.SetBackgroundColor(chronoirr.ChColor(0, 0, 0))
    vis.SetLighting(chronoirr.ChVisualSystemIrrlicht.Lighting_NONE)
    vis.SetColor(chronoirr.ChColor(255, 255, 255))
    vis.SetLighting(chronoirr.ChVisualSystemIrrlicht.Lighting_POINT)
    vis.SetLightPosition(ch.ChVector3d(10, 10, 10))
    vis.SetLightColor(chronoirr.ChColor(255, 255, 255))
    vis.SetLightIntensity(1.0)
    vis.SetShadowMapResolution(2048)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(1024, 1024)
    vis.SetLightDirection(ch.ChVector3d(0, 0, -1))
    vis.SetShadowMapResolution(1024, 1024)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(512, 512)
    vis.SetShadowMapResolution(512, 512)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(256, 256)
    vis.SetShadowMapResolution(256, 256)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(128, 128)
    vis.SetShadowMapResolution(128, 128)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(64, 64)
    vis.SetShadowMapResolution(64, 64)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(32, 32)
    vis.SetShadowMapResolution(32, 32)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(16, 16)
    vis.SetShadowMapResolution(16, 16)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(8, 8)
    vis.SetShadowMapResolution(8, 8)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(4, 4)
    vis.SetShadowMapResolution(4, 4)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(2, 2)
    vis.SetShadowMapResolution(2, 2)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(1, 1)
    vis.SetShadowMapResolution(1, 1)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadowMapFade(0.2)
    vis.SetShadowMapSize(0, 0)
    vis.SetShadowMapResolution(0, 0)
    vis.SetShadow