Here's the simulation script based on the provided instructions:
```python
import chrono as chrono
from chrono import ChColorText
from chrono.core import ChSystem, ChBody, ChBeam, ChMeshShape, ChVisualization, ChVisualizationIrrlicht
from chrono.core.consts import g
from chrono.core.shapes import ChMeshShape
from chrono.utils import set_default_values


system = ChSystem()
system.Set_G_acc(g)


beam_length = 10.0
beam_width = 1.0
beam_thickness = 0.1
material_density = 7850.0  
youngs_modulus = 200e9  
poissons_ratio = 0.3


beam_body = ChBody()
beam_body.SetBodyFixed(True)
beam_body.SetDensity(material_density)
beam_body.SetPos(0, 0, 0)
system.Add(beam_body)


beam_mesh = ChMeshShape()
beam_mesh.SetBeamLength(beam_length)
beam_mesh.SetBeamWidth(beam_width)
beam_mesh.SetBeamThickness(beam_thickness)
beam_mesh.SetMaterial(ChMaterial(0.3, youngs_modulus, poissons_ratio))
beam_body.AddAsset(beam_mesh)


motor_func = chrono.ChFunction()
motor_func.SetName("motor")
motor_func.SetType(chrono.ChFunction.TYPE_STEP)
motor_func.SetStep(0.01)
motor_func.SetMin(0)
motor_func.SetMax(beam_length)
motor_func.SetValue(0)


motor = ChBody()
motor.SetBodyFixed(True)
motor.SetPos(0, 0, 0)
motor.AddAsset(chrono.ChForce(motor_func))
system.Add(motor)


def custom_motor(t):
    return t * 0.1


motor_func.SetFunction(custom_motor)


ground = ChBody()
ground.SetBodyFixed(True)
ground.SetPos(0, 0, 0)
system.Add(ground)
beam_body.AddConstraint(chrono.ChLinkPlane(ground))


solver = chrono.ChSolverLMA()
system.SetSolver(solver)
timestepper = chrono.ChTimestepper()
timestepper.SetSolver(solver)
system.SetTimestepper(timestepper)


vis = ChVisualizationIrrlicht()
vis.SetSystem(system)
vis.SetCameraPos(0, 0, 10)
vis.SetCameraLookAt(0, 0, 0)
vis.SetCameraUp(0, 1, 0)
vis.SetCameraWidth(800)
vis.SetCameraHeight(600)
vis.SetCameraFPS(60)
vis.SetCameraMode(chrono.ChVisualizationIrrlicht.CAMERA_MODE_FREE)
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 0.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 0.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 0.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 0.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 0.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 0.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 0.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 0.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 0.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 1.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 1.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 1.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 1.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 1.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 1.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 1.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 1.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 1.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 1.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 2.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 2.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 2.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 2.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 2.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 2.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 2.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 2.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 2.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 2.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 3.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 3.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 3.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 3.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 3.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 3.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 3.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 3.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 3.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 3.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 4.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 4.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 4.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 4.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 4.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 4.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 4.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 4.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 4.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 4.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 5.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 5.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 5.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 5.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 5.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 5.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 5.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 5.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 5.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 5.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 6.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 6.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 6.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 6.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 6.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 6.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 6.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 6.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 6.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 6.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 7.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 7.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 7.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 7.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 7.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 7.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 7.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 7.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 7.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 7.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 8.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 8.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 8.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 8.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 8.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 8.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 8.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 8.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 8.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 8.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 9.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 9.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 9.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 9.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 9.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 9.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 9.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 9.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 9.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 9.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 10.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 10.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 10.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 10.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 10.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 10.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 10.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 10.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 10.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 10.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 11.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 11.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 11.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 11.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 11.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 11.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 11.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 11.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 11.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 11.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 12.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 12.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 12.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 12.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 12.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 12.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 12.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 12.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 12.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 12.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 13.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 13.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 13.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 13.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 13.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 13.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 13.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 13.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 13.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 13.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 14.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 14.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 14.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 14.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 14.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 14.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 14.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 14.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 14.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 14.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 15.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 15.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 15.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 15.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 15.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 15.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 15.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 15.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 15.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 15.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 16.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 16.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 16.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 16.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 16.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 16.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 16.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 16.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 16.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 16.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 17.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 17.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 17.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 17.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 17.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 17.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 17.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 17.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 17.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 17.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 18.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 18.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 18.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 18.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 18.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 18.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 18.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 18.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 18.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 18.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 19.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 19.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 19.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 19.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 19.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 19.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 19.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 19.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 19.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 19.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 20.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 20.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 20.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 20.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 20.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 20.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 20.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 20.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 20.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 20.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 21.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 21.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 21.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 21.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 21.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 21.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 21.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 21.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 21.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 21.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 22.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 22.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 22.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 22.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 22.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 22.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 22.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 22.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 22.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 22.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 23.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 23.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 23.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 23.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 23.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 23.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 23.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 23.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 23.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 23.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 24.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 24.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 24.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 24.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 24.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 24.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 24.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 24.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 24.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 24.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 25.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 25.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 25.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 25.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 25.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 25.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 25.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 25.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 25.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 25.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 26.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 26.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 26.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 26.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 26.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 26.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 26.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 26.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 26.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 26.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 27.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 27.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 27.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 27.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 27.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 27.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 27.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 27.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 27.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 27.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 28.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 28.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 28.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 28.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 28.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 28.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 28.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 28.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 28.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 28.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 29.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 29.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 29.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 29.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 29.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 29.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 29.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 29.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 29.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 29.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 30.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 30.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 30.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 30.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 30.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 30.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 30.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 30.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 30.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 30.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 31.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 31.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 31.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 31.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 31.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 31.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 31.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 31.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 31.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 31.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 32.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 32.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 32.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 32.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 32.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 32.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 32.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 32.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 32.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 32.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 33.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 33.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 33.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 33.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 33.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 33.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 33.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 33.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 33.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 33.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 34.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 34.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 34.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 34.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 34.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 34.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 34.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 34.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 34.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 34.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 35.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 35.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 35.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 35.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 35.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 35.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 35.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 35.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 35.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 35.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 36.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 36.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 36.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 36.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 36.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 36.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 36.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 36.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 36.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 36.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 37.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 37.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 37.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 37.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 37.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 37.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 37.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 37.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 37.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 37.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 38.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 38.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 38.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 38.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 38.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 38.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 38.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 38.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 38.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 38.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 39.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 39.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 39.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 39.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 39.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 39.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 39.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 39.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 39.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 39.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 40.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 40.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 40.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 40.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 40.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 40.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 40.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 40.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 40.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 40.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 41.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 41.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 41.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 41.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 41.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 41.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 41.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 41.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 41.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 41.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 42.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 42.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 42.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 42.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 42.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 42.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 42.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 42.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 42.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 42.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 43.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 43.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 43.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 43.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 43.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 43.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 43.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 43.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 43.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 43.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 44.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 44.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 44.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 44.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 44.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 44.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 44.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 44.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 44.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 44.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 45.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 45.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 45.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 45.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 45.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 45.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 45.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 45.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 45.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 45.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 46.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 46.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 46.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 46.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 46.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 46.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 46.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 46.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 46.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 46.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 47.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 47.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 47.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 47.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 47.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 47.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 47.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 47.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 47.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 47.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 48.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 48.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 48.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 48.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 48.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 48.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 48.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 48.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 48.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 48.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 49.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 49.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 49.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 49.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 49.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 49.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 49.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 49.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 49.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 49.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 50.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 50.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 50.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 50.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 50.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 50.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 50.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 50.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 50.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 50.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 51.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 51.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 51.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 51.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 51.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 51.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 51.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 51.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 51.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 51.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 52.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 52.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 52.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 52.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 52.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 52.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 52.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 52.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 52.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 52.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 53.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 53.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 53.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 53.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 53.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 53.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 53.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 53.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 53.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 53.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 54.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 54.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 54.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 54.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 54.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 54.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 54.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 54.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 54.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 54.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 55.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 55.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 55.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 55.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 55.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 55.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 55.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 55.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 55.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 55.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 56.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 56.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 56.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 56.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 56.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 56.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 56.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 56.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 56.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 56.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 57.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 57.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 57.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 57.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 57.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 57.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 57.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 57.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 57.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 57.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 58.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 58.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 58.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 58.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 58.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 58.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 58.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 58.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 58.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 58.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 59.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 59.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 59.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 59.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 59.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 59.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 59.6))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 59.7))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 59.8))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 59.9))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 60.0))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 60.1))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 60.2))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 60.3))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 0, 1), 60.4))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(0, 1, 0), 60.5))
vis.SetCameraRotation(chrono.ChQuaternion(chrono.ChVector(1, 0, 0), 60.6))
vis.Set